import './css/style.css';

import { Inter } from 'next/font/google';

import Header from '@/components/ui/header';
import { AntdRegistry } from '@ant-design/nextjs-registry';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} bg-white font-inter tracking-tight text-gray-900 antialiased`}
      >
        <AntdRegistry>
          <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
            <Header />
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
